src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède déjà ce titre, merci de le modifier !"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  min = 10,
     *  max = 255,
     *  minMessage = "Le titre doit être supérieur à 10 caractères",
     *  maxMessage = "Le titre ne doit pas dépasser 255 caractères"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *  min = 20,
     *  minMessage = "L'introduction doit être supérieur à 20 caractères"
     * )
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *  min = 100,
     *  minMessage = "La descrition doit être supérieur à 100 caractères"
     * )
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Allow to initialize the slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug()
    {
        if(empty($this->slug)){
            // Instanciation of Slugify class
            $slugify = new Slugify();

            // Affectation of the slug propertie with the slugify methods
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Allow to get the comment of the user which have been doing a booking of this ad
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author)return $comment;
        }

        return null;
    }

    /**
     * Allow to return the ratings average for this ad
     *
     * @return float
     */
    public function getAvgRatings()
    {
        // We must to know the sum of ratings
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);

        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Allow to get an array of days wich are not available for this ad
     *
     * @return array Object array DateTime which represent occupation days 
     */
    public function getNotAvailableDays()
    {
        // We initialize an array which will to save the not available days
        $notAvailableDays = [];

        foreach($this->bookings as $booking){
            // Calculate the days which are between start date and end date
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            // We convert the timestamp dates in real date with good format
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            // We merge the notAvailableDays array with days array
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        // We return the not available days in to an array
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ApplicationType;
use App\Form\ImageType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'title',
                TextType::class,
                $this->getConfigurations("Titre de l'annonce", "Tapez un super titre")
            )
            ->add(
                'slug',
                TextType::class,
                $this->getConfigurations("Slug de l'annonce", "Entrez le slug",[
                    'required' => false
                ])
            )
            ->add(
                'coverImage',
                UrlType::class,
                $this->getConfigurations("Url de l'image", "Ajoutez l'url de l'image principale")
            )
            ->add(
                'introduction',
                TextType::class,
                $this->getConfigurations("Introduction", "Ecrivez une petite introduction")
            )
            ->add(
                'content',
                TextareaType::class,
                $this->getConfigurations("Description", "Décrivez votre bien")
            )
            ->add(
                'rooms',
                IntegerType::class,
                $this->getConfigurations("Nombre de chambres", "Renseignez le nombre de chambre")
            )
            ->add(
                'price',
                MoneyType::class,
                $this->getConfigurations("Prix de l'annonce", "Entrez le prix")
            )
            ->add(
                'images',
                CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;
use App\Repository\AdRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {
        // We get all ads
        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }

    /**
     * Allow to create an Ad
     * 
     * @Route("/ads/new", name="ads_create")
     * @IsGranted(
     *  "ROLE_USER",
     *  message="Vous devez être connecté pour pouvoir créer une annonce !"
     * )
     *
     * @return Response
     */
    public function create(Request $request, ObjectManager $manager)
    {
        // Instanciation of a new ad
        $ad = new Ad();

        // Construction a form with the formBuilder
        $form = $this->createForm(AdType::class, $ad);

        // Handle http request in to form
        $form->handleRequest($request);
        
        // Test if form have been submitted and if it's valid
        if($form->isSubmitted() && $form->isValid()){
            // We persist all images which have been added
            foreach($ad->getImages() as $image){
                // We link the image with current ad
                $image->setAd($ad);
                // We persist this image
                $manager->persist($image);
            }

            // Linking with the user which is login
            $ad->setAuthor($this->getUser());

            // We persit the new ad entity
            $manager->persist($ad);
            dump($ad);

            // We send the sql request in to database in order to save this new ad
            $manager->flush();

            // Sending a flash success which show that the ad have been saving in to database
            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a été créée avec succès !"
            );
            
            // Redirect to route which show this new ad
            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        // Return in to a view and give to twig the variable form which will create the form template
        return $this->render(
            'ad/new.html.twig',
            ['form' => $form->createView()]
        );

    }
    
    /**
     * Allow to implement the edit form of an ad
     * 
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @Security(
     *  "is_granted('ROLE_USER') and user === ad.getAuthor()",
     *  message ="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier !"
     * )
     *
     * @return Response
     */
    public function edit(Request $request, Ad $ad, ObjectManager $manager){
        // Construction a form with the formBuilder
        $form = $this->createForm(AdType::class, $ad);

        // Handle http request in to form
        $form->handleRequest($request);

        // Test if form have been submitted
        if($form->isSubmitted() && $form->isValid()){
            // We persist all images which have been added
            foreach($ad->getImages() as $image){
                // We link the image with current ad
                $image->setAd($ad);
                // We persist this image
                $manager->persist($image);
            }
            // We persit the new ad entity
            $manager->persist($ad);
            dump($ad);

            // We send the sql request in to database in order to save this new ad
            $manager->flush();

            // Sending a flash success which show that the ad have been saving in to database
            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a été modifiée avec succès !"
            );
            
            // Redirect to route which show this new ad
            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render("ad/edit.html.twig", [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Allow to show an ad
     *
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad)
    {
        return $this->render(
                "ad/show.html.twig",
                [
                    'ad' => $ad
                ]
            );
    }

    /**
     * Allow to delete an ad
     *
     * @Route("ads/{slug}/delete", name="ads_delete")
     * @Security(
     *  "is_granted('ROLE_USER') and user === ad.getAuthor()",
     *  message="Vous n'avez pas le droit d'accéder à cette ressource !"
     * )
     * 
     * @param Ad $ad
     * @param ObjectManager $manager
     * 
     * @return Response
     */
    public function delete(Ad $ad, ObjectManager $manager)
    {
        // We ask to manage to remove the ad which have been selectionned
        $manager->remove($ad);

        // We sent the sql request to database
        $manager->flush();
        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a été supprimée avec succès"
        );

        return $this->redirectToRoute("ads_index");
    }
    
}

templates/ad/_ad.html.twig
{% set ad_show = path("ads_show", {'slug': ad.slug}) %}

<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price | number_format(2, ',', ' ')}}&euro; par nuit</strong> <br>
            {% if ad.comments|length > 0 %}
                {% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <a href="{{ ad_show }}">
            <img src="{{ ad.coverImage }}" alt="Image de l'appartement" style="height: 200px; width: 100%; display: block;">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ ad_show }}" class="text-muted">
                    {{ ad.title }}
                </a>
            </h4> 
            <p class="card-text">
                {{ ad.introduction }}
            </p>
            <a href="{{ ad_show }}" class="btn btn-primary float-right">En savoir plus !</a> 
            {% if app.user and ad.author == app.user %}
                <a href="{{ path("ads_edit",{'slug': ad.slug}) }}" class="btn btn-secondary">Editer</a>
                <a href="{{path('ads_delete',{'slug': ad.slug }) }}" onclick="return confirm(`Etes vous sûr de vouloir supprimer l'annonce {{ ad.title }} ?`)" class="btn btn-danger">Supprimer l'annonce</a>
            {% endif %}
        </div>
    </div> 
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images !</p>

    {{ form_widget(form) }}

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image &nbsp; <i class="fas fa-plus"></i></button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group " id='block_{{id}}'>
    {{ form_errors(form) }}
        <div class="row">
            <div class="col-10">
                <div class="row">
                    {% if value %}
                        <div class="col-2">
                            <img src="{{value.url}}" class="rounded" style="width:48px;height:48px" alt="">
                        </div>
                    {% endif %}
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{id}}"><i class="fas fa-trash"></i></button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modification d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Modifier l'annonce : {{ ad.title }}</h1>

        {{ form_start(form) }}

        {{ form_widget(form) }}

        <input type="hidden" id="widgets-counter" value="0">
        
        <button class="btn btn-primary">Enregistrer les modifications</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-5">Voici les annonces de nos hôtes !</h1>
        <div class="row">
            {% for ad in ads %}
                {% include "ad/_ad.html.twig" %}
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1 class="my-5">Créer une nouvelle annonce</h1>

        {{ form_start(form) }}

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Informations générales</h2>
                    <hr>
                    {{ form_row(form.title) }}
                    {{ form_row(form.slug) }}
                    {{ form_row(form.price) }}
                    {{ form_row(form.rooms) }}
                </div>
                <div class="alert alert-light">
                    <h2>Détails de l'annonce</h2>
                    <hr>
                    {{ form_row(form.introduction) }}
                    {{ form_row(form.content) }}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2>Image de l'annonce</h2>
                    <hr>
                    {{ form_row(form.coverImage) }}
                    {{ form_row(form.images) }}
                </div>
            </div>
        </div>
        <div class="alert alert-success text-center">
            <div class="row">
                <div class="col ">
                    <h2 class="alert-heading">Sauvegarder mon annonce</h2>
                    <p>Vous êtes sur le point de créer votre annonce !</p>
                </div>
                <div class="col">
                    <br>
                    <button class="btn btn-primary">Créer une nouvelle annonce <i class="fas fa-check"></i></button>
                </div>
            </div>
        </div>
        <input type="hidden" id="widgets-counter" value="0">
        
        
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ ad.title }} {% endblock %}

{% block body %}
<div class="ad-titre" style="background-image: url({{ ad.coverImage }});">
    <div class="container">
        <h1>{{ ad.title }}</h1>
        <p>{{ ad.introduction }}</p>
        <p class="h2">
            <strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price | number_format(2, ',', ' ') }} &euro; </strong> par nuit
        </p>
        <a href="{{ path('booking_create', {'slug': ad.slug}) }}" class="btn btn-primary">Réserver !</a>
        {% if app.user and ad.author == app.user %}
            <a href="{{ path("ads_edit",{'slug': ad.slug}) }}" class="btn btn-primary">Editer</a>
            <a href="{{path('ads_delete',{'slug': ad.slug }) }}" onclick="return confirm(`Etes vous sûr de vouloir supprimer l'annonce {{ ad.title }} ?`)" class="btn btn-danger">Supprimer l'annonce</a>
        {% endif %}
        
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8 mb-3">

            {{ ad.content|raw }}

            <div id="carouselExampleCaptions" class="carousel slide shadow" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                        <li data-target="#carouselExampleCaptions" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                    {% endfor %} 
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %}active{% endif %}">
                            <img src=" {{ image.url }} " class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ ad.title }}</h5>
                                <p>{{ image.caption }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Précédente</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Suivante</span>
                </a>
            </div>

            <hr>

            {% if ad.comments|length > 0 %}
                <h2 class="mb-3">Commentaires de nos voyageurs :</h2>

                <div class="alert alert-info shadow">
                    <h4 class="alert-heading text-center">
                        <div class="row align-items-center">
                            <div class="col">
                                Note globale donnée par nos voyageurs 
                            </div>
                            <div class="col">
                                {% include "partials/rating.html.twig" with {'rating': ad.avgRatings }%}
                                <br>
                                <small>(Calculée sur {{ad.comments|length}} avis !)</small>
                            </div>
                        </div>
                    </h4>
                </div>

                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3 shadow">
                        <strong>{{comment.author.fistName}}</strong> a dit : 
                        <blockquote>
                            {{comment.content}}
                        </blockquote>
                        <strong>Note donnée : </strong>
                        {% set rating = comment.rating %}
                        {% include "partials/rating.html.twig" with {'rating': comment.rating }%}
                    </div>
                {% endfor %}
            {% else %}
                <h2>Cette annonce n'a pas encore reçu de commentaires</h2>
            {% endif %}

        </div>

        <div class="col">
            {% set a = ad.author %}
            <div class="row mb-2">
                <div class="col-3">
                    <a href="{{ path("user_show",{'slug': a.slug}) }}">
                        <img src="{{a.picture}}" alt="Avatar de {{ a.getFullName }}" class="avatar avatar-medium">
                    </a>
                </div>
                <div class="col">
                    <a href="{{ path("user_show",{'slug': a.slug}) }}">
                        <h3>{{ a.getFullName }}</h3>
                    </a>
                    <span class="badge badge-primary font-weight-bold">{{ a.ads|length }} annonces</span>
                </div>
            </div>
            {{ a.description|raw }}
        </div>
    </div>
</div>
{% endblock %}